### ISSUE TITLE
i am getting this issue : docker: failed to register layer: devmapper: Error activating devmapper device for '05e2cc172ff3381082a9dababfb86ffe1e062e78d7b7badb27bb9e8b45c60cd4': devicemapper: Can't set cookie dm_task_set_cookie failed.

### ISSUE THREAD

**Issue by arezki1990** [jpetazzo/nsenter#88]
this is the entire log when I tried to execute the cmd docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter

Unable to find image 'jpetazzo/nsenter:latest' locally
latest: Pulling from jpetazzo/nsenter
5c90d4a2d1a8: Extracting [==================================================>]  51.35MB/51.35MB
c6c4c486dd77: Download complete 
0ed6ac9f06ed: Download complete 
404416bec766: Download complete 
4bf954ba4ae2: Download complete 
23f698ff1fd0: Download complete 
b39fba43fbdb: Download complete 
7889943d47f6: Download complete 
446df4bc8efe: Download complete 
6074415f722e: Download complete 
72024cea4c47: Download complete 
6c4b4f4219d3: Download complete 
93da7ec1688f: Download complete 
0c4337c5a938: Download complete 
docker: failed to register layer: devmapper: Error activating devmapper device for '05e2cc172ff3381082a9dababfb86ffe1e062e78d7b7badb27bb9e8b45c60cd4': devicemapper: Can't set cookie dm_task_set_cookie failed.
See 'docker run --help'.

**Comment by jpetazzo** [comment]
Whoa, that's a really weird bug!

I'd recommend that you use `docker exec` instead of nsenter.

But if you really want to use nsenter... Then, can you confirm:
- which version of Docker you're running
- if the command works without the `-v /usr/local/bin:/target` option
- if you can run e.g. `docker run -v /usr/local/bin:/target alpine sleep 5`
